# Aggregate Tier-1 Results

Coverage and public aggregate comparisons for all seven Tier-1 methods.

This executed notebook uses only public prompts, responses, and aggregate analysis. It does not embed answer keys or row-level correctness labels.

In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

root = Path.cwd().resolve()
manifest_path = root / 'tier1_manifest.json'
manifest = json.loads(manifest_path.read_text(encoding='utf-8')) if manifest_path.exists() else {}

def read_public_csv(path):
    if not path.exists():
        return pd.DataFrame()
    frame = pd.read_csv(path, keep_default_na=False)
    forbidden = {'gold', 'ground_truth', 'correct_answer', 'normalized_gold', 'is_correct'}
    exposed = forbidden.intersection(str(column).lower() for column in frame.columns)
    if exposed:
        raise ValueError(f'public analysis contains forbidden row-level columns: {sorted(exposed)}')
    return frame

print('model:', manifest.get('model', 'not prepared'))
print('reasoning effort:', manifest.get('reasoning_effort', 'not prepared'))
print('prompt version:', manifest.get('prompt_version', 'not prepared'))

model: gpt-5.6-sol
reasoning effort: high
prompt version: gpt56-tier1-v1

In [2]:
expected = {
    'normalize_then_solve': 250,
    'structured_decomposition': 250,
    'explicit_task_instructions': 200,
    'chain_of_thought': 450,
    'rereading_s2a': 200,
    'self_consistency_path_1': 450,
    'self_consistency_path_2': 450,
    'self_consistency_path_3': 450,
    'self_verification_cove_initial': 450,
    'self_verification_cove_verification': 450,
}
coverage = []
for queue, expected_rows in expected.items():
    dataset = read_public_csv(root / 'Dataset' / f'{queue}.csv')
    result = read_public_csv(root / 'Result' / f'{queue}.csv')
    answered = 0 if result.empty else int(result['model_response'].astype(str).str.strip().ne('').sum())
    coverage.append({
        'queue': queue,
        'expected_rows': expected_rows,
        'dataset_rows': len(dataset),
        'result_rows': len(result),
        'answered_rows': answered,
    })
coverage_frame = pd.DataFrame(coverage)
display(coverage_frame)
print('planned scored evaluation units:', sum((250, 250, 200, 450, 200, 450, 450)))
print('planned raw generations:', sum(expected.values()))

analysis_dir = root / 'Analysis'
if analysis_dir.exists():
    for path in sorted(analysis_dir.glob('*.csv')):
        frame = read_public_csv(path)
        print(path.name)
        if 'evaluation_id' in frame.columns and len(frame) > 100:
            print('public row-level aggregate rows:', len(frame))
            grouping = [column for column in ('condition', 'task', 'variant', 'agreement', 'status', 'answer_changed') if column in frame]
            if grouping:
                display(frame.groupby(grouping, dropna=False).size().rename('rows').reset_index())
        else:
            display(frame)
    summary_path = analysis_dir / 'summary.json'
    if summary_path.exists():
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        safe_keys = {
            'model', 'reasoning_effort', 'prompt_version', 'scoring_policy',
            'conditions', 'task_variant_cells', 'evaluation_units',
            'raw_model_generations', 'completed_evaluations', 'condition_totals',
            'special_metrics', 'status_counts',
        }
        display({key: value for key, value in summary.items() if key in safe_keys})
    aggregation_path = analysis_dir / 'aggregation_summary.json'
    if aggregation_path.exists():
        display(json.loads(aggregation_path.read_text(encoding='utf-8')))
else:
    print('Analysis directory is not available yet.')

,queue,expected_rows,dataset_rows,result_rows,answered_rows
0,normalize_then_solve,250,250,250,250
1,structured_decomposition,250,250,250,250
2,explicit_task_instructions,200,200,200,200
3,chain_of_thought,450,450,450,450
4,rereading_s2a,200,200,200,200
5,self_consistency_path_1,450,450,450,450
6,self_consistency_path_2,450,450,450,450
7,self_consistency_path_3,450,450,450,450
8,self_verification_cove_initial,450,450,450,450
9,self_verification_cove_verification,450,450,450,450

planned scored evaluation units: 2250
planned raw generations: 3600
accuracy_by_cell.csv

,model,condition,task,task_title,variant,correct,total,accuracy_pct,response_or_consensus_failures
0,gpt-5.6-sol,normalize_then_solve,obfus_fol,FOL,base,44,50,88.0,0
1,gpt-5.6-sol,normalize_then_solve,obfus_fol,FOL,obfuscation,33,50,66.0,0
2,gpt-5.6-sol,normalize_then_solve,obfus_blood_relation,Blood Relation,base,39,50,78.0,0
3,gpt-5.6-sol,normalize_then_solve,obfus_blood_relation,Blood Relation,obfuscation_l1,34,50,68.0,0
4,gpt-5.6-sol,normalize_then_solve,obfus_blood_relation,Blood Relation,obfuscation_l2,31,50,62.0,0
5,gpt-5.6-sol,structured_decomposition,obfus_blood_relation,Blood Relation,base,39,50,78.0,0
6,gpt-5.6-sol,structured_decomposition,obfus_blood_relation,Blood Relation,obfuscation_l1,34,50,68.0,0
7,gpt-5.6-sol,structured_decomposition,obfus_blood_relation,Blood Relation,obfuscation_l2,31,50,62.0,0
8,gpt-5.6-sol,structured_decomposition,obfus_direction_sense,Direction Sense,base,23,50,46.0,0
9,gpt-5.6-sol,structured_decomposition,obfus_direction_sense,Direction Sense,obfuscation,19,50,38.0,0
10,gpt-5.6-sol,explicit_task_instructions,obfus_number_series,Number Series,base,41,50,82.0,0
11,gpt-5.6-sol,explicit_task_instructions,obfus_number_series,Number Series,obfuscation,41,50,82.0,0
12,gpt-5.6-sol,explicit_task_instructions,obfus_direction_sense,Direction Sense,base,24,50,48.0,0
13,gpt-5.6-sol,explicit_task_instructions,obfus_direction_sense,Direction Sense,obfuscation,19,50,38.0,0
14,gpt-5.6-sol,chain_of_thought,obfus_fol,FOL,base,43,50,86.0,0
15,gpt-5.6-sol,chain_of_thought,obfus_fol,FOL,obfuscation,34,50,68.0,0
16,gpt-5.6-sol,chain_of_thought,obfus_blood_relation,Blood Relation,base,42,50,84.0,0
17,gpt-5.6-sol,chain_of_thought,obfus_blood_relation,Blood Relation,obfuscation_l1,41,50,82.0,0
18,gpt-5.6-sol,chain_of_thought,obfus_blood_relation,Blood Relation,obfuscation_l2,41,50,82.0,0
19,gpt-5.6-sol,chain_of_thought,obfus_number_series,Number Series,base,41,50,82.0,0
20,gpt-5.6-sol,chain_of_thought,obfus_number_series,Number Series,obfuscation,41,50,82.0,0
21,gpt-5.6-sol,chain_of_thought,obfus_direction_sense,Direction Sense,base,24,50,48.0,0
22,gpt-5.6-sol,chain_of_thought,obfus_direction_sense,Direction Sense,obfuscation,19,50,38.0,0
23,gpt-5.6-sol,rereading_s2a,obfus_fol,FOL,base,42,50,84.0,0
24,gpt-5.6-sol,rereading_s2a,obfus_fol,FOL,obfuscation,35,50,70.0,0
25,gpt-5.6-sol,rereading_s2a,obfus_blood_relation,Blood Relation,base,38,50,76.0,0
26,gpt-5.6-sol,rereading_s2a,obfus_blood_relation,Blood Relation,obfuscation_l2,36,50,72.0,0
27,gpt-5.6-sol,self_consistency,obfus_fol,FOL,base,44,50,88.0,0
28,gpt-5.6-sol,self_consistency,obfus_fol,FOL,obfuscation,32,50,64.0,0
29,gpt-5.6-sol,self_consistency,obfus_blood_relation,Blood Relation,base,39,50,78.0,0
30,gpt-5.6-sol,self_consistency,obfus_blood_relation,Blood Relation,obfuscation_l1,35,50,70.0,2
31,gpt-5.6-sol,self_consistency,obfus_blood_relation,Blood Relation,obfuscation_l2,34,50,68.0,1
32,gpt-5.6-sol,self_consistency,obfus_number_series,Number Series,base,41,50,82.0,2
33,gpt-5.6-sol,self_consistency,obfus_number_series,Number Series,obfuscation,41,50,82.0,2
34,gpt-5.6-sol,self_consistency,obfus_direction_sense,Direction Sense,base,24,50,48.0,0
35,gpt-5.6-sol,self_consistency,obfus_direction_sense,Direction Sense,obfuscation,20,50,40.0,0
36,gpt-5.6-sol,self_verification_cove,obfus_fol,FOL,base,41,50,82.0,0
37,gpt-5.6-sol,self_verification_cove,obfus_fol,FOL,obfuscation,32,50,64.0,0
38,gpt-5.6-sol,self_verification_cove,obfus_blood_relation,Blood Relation,base,38,50,76.0,0
39,gpt-5.6-sol,self_verification_cove,obfus_blood_relation,Blood Relation,obfuscation_l1,35,50,70.0,0
40,gpt-5.6-sol,self_verification_cove,obfus_blood_relation,Blood Relation,obfuscation_l2,36,50,72.0,0
41,gpt-5.6-sol,self_verification_cove,obfus_number_series,Number Series,base,40,50,80.0,0
42,gpt-5.6-sol,self_verification_cove,obfus_number_series,Number Series,obfuscation,40,50,80.0,0
43,gpt-5.6-sol,self_verification_cove,obfus_direction_sense,Direction Sense,base,24,50,48.0,0
44,gpt-5.6-sol,self_verification_cove,obfus_direction_sense,Direction Sense,obfuscation,20,50,40.0,0

base_obfuscated_gaps.csv

,condition,task,variant,base_source_condition,base_correct,obfuscated_correct,total,base_accuracy_pct,obfuscated_accuracy_pct,base_minus_obfuscated_pp
0,normalize_then_solve,obfus_fol,obfuscation,normalize_then_solve,44,33,50,88.0,66.0,22.0
1,normalize_then_solve,obfus_blood_relation,obfuscation_l1,normalize_then_solve,39,34,50,78.0,68.0,10.0
2,normalize_then_solve,obfus_blood_relation,obfuscation_l2,normalize_then_solve,39,31,50,78.0,62.0,16.0
3,structured_decomposition,obfus_blood_relation,obfuscation_l1,structured_decomposition,39,34,50,78.0,68.0,10.0
4,structured_decomposition,obfus_blood_relation,obfuscation_l2,structured_decomposition,39,31,50,78.0,62.0,16.0
5,structured_decomposition,obfus_direction_sense,obfuscation,structured_decomposition,23,19,50,46.0,38.0,8.0
6,explicit_task_instructions,obfus_number_series,obfuscation,explicit_task_instructions,41,41,50,82.0,82.0,0.0
7,explicit_task_instructions,obfus_direction_sense,obfuscation,explicit_task_instructions,24,19,50,48.0,38.0,10.0
8,chain_of_thought,obfus_fol,obfuscation,chain_of_thought,43,34,50,86.0,68.0,18.0
9,chain_of_thought,obfus_blood_relation,obfuscation_l1,chain_of_thought,42,41,50,84.0,82.0,2.0
10,chain_of_thought,obfus_blood_relation,obfuscation_l2,chain_of_thought,42,41,50,84.0,82.0,2.0
11,chain_of_thought,obfus_number_series,obfuscation,chain_of_thought,41,41,50,82.0,82.0,0.0
12,chain_of_thought,obfus_direction_sense,obfuscation,chain_of_thought,24,19,50,48.0,38.0,10.0
13,rereading_s2a,obfus_fol,obfuscation,rereading_s2a,42,35,50,84.0,70.0,14.0
14,rereading_s2a,obfus_blood_relation,obfuscation_l2,rereading_s2a,38,36,50,76.0,72.0,4.0
15,self_consistency,obfus_fol,obfuscation,self_consistency,44,32,50,88.0,64.0,24.0
16,self_consistency,obfus_blood_relation,obfuscation_l1,self_consistency,39,35,50,78.0,70.0,8.0
17,self_consistency,obfus_blood_relation,obfuscation_l2,self_consistency,39,34,50,78.0,68.0,10.0
18,self_consistency,obfus_number_series,obfuscation,self_consistency,41,41,50,82.0,82.0,0.0
19,self_consistency,obfus_direction_sense,obfuscation,self_consistency,24,20,50,48.0,40.0,8.0
20,self_verification_cove,obfus_fol,obfuscation,self_verification_cove,41,32,50,82.0,64.0,18.0
21,self_verification_cove,obfus_blood_relation,obfuscation_l1,self_verification_cove,38,35,50,76.0,70.0,6.0
22,self_verification_cove,obfus_blood_relation,obfuscation_l2,self_verification_cove,38,36,50,76.0,72.0,4.0
23,self_verification_cove,obfus_number_series,obfuscation,self_verification_cove,40,40,50,80.0,80.0,0.0
24,self_verification_cove,obfus_direction_sense,obfuscation,self_verification_cove,24,20,50,48.0,40.0,8.0

condition_totals.csv

,condition,scope,correct,total,accuracy_pct
0,normalize_then_solve,all applicable variants,181,250,72.4000
1,normalize_then_solve,obfuscated variants,98,150,65.3333
2,structured_decomposition,all applicable variants,146,250,58.4000
3,structured_decomposition,obfuscated variants,84,150,56.0000
4,explicit_task_instructions,all applicable variants,125,200,62.5000
5,explicit_task_instructions,obfuscated variants,60,100,60.0000
6,chain_of_thought,all applicable variants,326,450,72.4444
7,chain_of_thought,obfuscated variants,176,250,70.4000
8,rereading_s2a,all applicable variants,151,200,75.5000
9,rereading_s2a,obfuscated variants,71,100,71.0000
10,self_consistency,all applicable variants,310,450,68.8889
11,self_consistency,obfuscated variants,162,250,64.8000
12,self_verification_cove,all applicable variants,306,450,68.0000
13,self_verification_cove,obfuscated variants,163,250,65.2000

cove_aggregates.csv
public row-level aggregate rows: 450

,condition,task,variant,status,answer_changed,rows
0,self_verification_cove,obfus_blood_relation,base,answered,False,50
1,self_verification_cove,obfus_blood_relation,obfuscation_l1,answered,False,50
2,self_verification_cove,obfus_blood_relation,obfuscation_l2,answered,False,50
3,self_verification_cove,obfus_direction_sense,base,answered,False,50
4,self_verification_cove,obfus_direction_sense,obfuscation,answered,False,48
5,self_verification_cove,obfus_direction_sense,obfuscation,answered,True,2
6,self_verification_cove,obfus_fol,base,answered,False,49
7,self_verification_cove,obfus_fol,base,answered,True,1
8,self_verification_cove,obfus_fol,obfuscation,answered,False,47
9,self_verification_cove,obfus_fol,obfuscation,answered,True,3
10,self_verification_cove,obfus_number_series,base,answered,False,50
11,self_verification_cove,obfus_number_series,obfuscation,answered,False,50

improvement_over_control.csv

,condition,task,variant,method_correct,control_correct,total,method_accuracy_pct,control_accuracy_pct,improvement_pp
0,normalize_then_solve,obfus_fol,obfuscation,33,30,50,66.0,60.0,6.0
1,normalize_then_solve,obfus_blood_relation,obfuscation_l1,34,36,50,68.0,72.0,-4.0
2,normalize_then_solve,obfus_blood_relation,obfuscation_l2,31,37,50,62.0,74.0,-12.0
3,structured_decomposition,obfus_blood_relation,obfuscation_l1,34,36,50,68.0,72.0,-4.0
4,structured_decomposition,obfus_blood_relation,obfuscation_l2,31,37,50,62.0,74.0,-12.0
5,structured_decomposition,obfus_direction_sense,obfuscation,19,18,50,38.0,36.0,2.0
6,explicit_task_instructions,obfus_number_series,obfuscation,41,42,50,82.0,84.0,-2.0
7,explicit_task_instructions,obfus_direction_sense,obfuscation,19,18,50,38.0,36.0,2.0
8,chain_of_thought,obfus_fol,obfuscation,34,30,50,68.0,60.0,8.0
9,chain_of_thought,obfus_blood_relation,obfuscation_l1,41,36,50,82.0,72.0,10.0
10,chain_of_thought,obfus_blood_relation,obfuscation_l2,41,37,50,82.0,74.0,8.0
11,chain_of_thought,obfus_number_series,obfuscation,41,42,50,82.0,84.0,-2.0
12,chain_of_thought,obfus_direction_sense,obfuscation,19,18,50,38.0,36.0,2.0
13,rereading_s2a,obfus_fol,obfuscation,35,30,50,70.0,60.0,10.0
14,rereading_s2a,obfus_blood_relation,obfuscation_l2,36,37,50,72.0,74.0,-2.0
15,self_consistency,obfus_fol,obfuscation,32,30,50,64.0,60.0,4.0
16,self_consistency,obfus_blood_relation,obfuscation_l1,35,36,50,70.0,72.0,-2.0
17,self_consistency,obfus_blood_relation,obfuscation_l2,34,37,50,68.0,74.0,-6.0
18,self_consistency,obfus_number_series,obfuscation,41,42,50,82.0,84.0,-2.0
19,self_consistency,obfus_direction_sense,obfuscation,20,18,50,40.0,36.0,4.0
20,self_verification_cove,obfus_fol,obfuscation,32,30,50,64.0,60.0,4.0
21,self_verification_cove,obfus_blood_relation,obfuscation_l1,35,36,50,70.0,72.0,-2.0
22,self_verification_cove,obfus_blood_relation,obfuscation_l2,36,37,50,72.0,74.0,-2.0
23,self_verification_cove,obfus_number_series,obfuscation,40,42,50,80.0,84.0,-4.0
24,self_verification_cove,obfus_direction_sense,obfuscation,20,18,50,40.0,36.0,4.0

paired_retention.csv

,condition,task,variant,both_correct,base_only_correct,obfuscated_only_correct,both_wrong,total,paired_retention_pct
0,normalize_then_solve,obfus_fol,obfuscation,32,12,1,5,50,72.7273
1,normalize_then_solve,obfus_blood_relation,obfuscation_l1,34,5,0,11,50,87.1795
2,normalize_then_solve,obfus_blood_relation,obfuscation_l2,31,8,0,11,50,79.4872
3,structured_decomposition,obfus_blood_relation,obfuscation_l1,34,5,0,11,50,87.1795
4,structured_decomposition,obfus_blood_relation,obfuscation_l2,31,8,0,11,50,79.4872
5,structured_decomposition,obfus_direction_sense,obfuscation,18,5,1,26,50,78.2609
6,explicit_task_instructions,obfus_number_series,obfuscation,41,0,0,9,50,100.0000
7,explicit_task_instructions,obfus_direction_sense,obfuscation,19,5,0,26,50,79.1667
8,chain_of_thought,obfus_fol,obfuscation,33,10,1,6,50,76.7442
9,chain_of_thought,obfus_blood_relation,obfuscation_l1,41,1,0,8,50,97.6190
10,chain_of_thought,obfus_blood_relation,obfuscation_l2,41,1,0,8,50,97.6190
11,chain_of_thought,obfus_number_series,obfuscation,41,0,0,9,50,100.0000
12,chain_of_thought,obfus_direction_sense,obfuscation,19,5,0,26,50,79.1667
13,rereading_s2a,obfus_fol,obfuscation,32,10,3,5,50,76.1905
14,rereading_s2a,obfus_blood_relation,obfuscation_l2,36,2,0,12,50,94.7368
15,self_consistency,obfus_fol,obfuscation,32,12,0,6,50,72.7273
16,self_consistency,obfus_blood_relation,obfuscation_l1,35,4,0,11,50,89.7436
17,self_consistency,obfus_blood_relation,obfuscation_l2,34,5,0,11,50,87.1795
18,self_consistency,obfus_number_series,obfuscation,41,0,0,9,50,100.0000
19,self_consistency,obfus_direction_sense,obfuscation,20,4,0,26,50,83.3333
20,self_verification_cove,obfus_fol,obfuscation,28,13,4,5,50,68.2927
21,self_verification_cove,obfus_blood_relation,obfuscation_l1,35,3,0,12,50,92.1053
22,self_verification_cove,obfus_blood_relation,obfuscation_l2,36,2,0,12,50,94.7368
23,self_verification_cove,obfus_number_series,obfuscation,40,0,0,10,50,100.0000
24,self_verification_cove,obfus_direction_sense,obfuscation,20,4,0,26,50,83.3333

self_consistency_aggregates.csv
public row-level aggregate rows: 450

,condition,task,variant,agreement,status,rows
0,self_consistency,obfus_blood_relation,base,majority,answered,3
1,self_consistency,obfus_blood_relation,base,unanimous,answered,47
2,self_consistency,obfus_blood_relation,obfuscation_l1,majority,answered,5
3,self_consistency,obfus_blood_relation,obfuscation_l1,none,no_consensus,2
4,self_consistency,obfus_blood_relation,obfuscation_l1,unanimous,answered,43
5,self_consistency,obfus_blood_relation,obfuscation_l2,majority,answered,6
6,self_consistency,obfus_blood_relation,obfuscation_l2,none,no_consensus,1
7,self_consistency,obfus_blood_relation,obfuscation_l2,unanimous,answered,43
8,self_consistency,obfus_direction_sense,base,majority,answered,17
9,self_consistency,obfus_direction_sense,base,unanimous,answered,33
10,self_consistency,obfus_direction_sense,obfuscation,majority,answered,14
11,self_consistency,obfus_direction_sense,obfuscation,unanimous,answered,36
12,self_consistency,obfus_fol,base,majority,answered,3
13,self_consistency,obfus_fol,base,unanimous,answered,47
14,self_consistency,obfus_fol,obfuscation,majority,answered,2
15,self_consistency,obfus_fol,obfuscation,unanimous,answered,48
16,self_consistency,obfus_number_series,base,majority,answered,4
17,self_consistency,obfus_number_series,base,none,no_consensus,2
18,self_consistency,obfus_number_series,base,unanimous,answered,44
19,self_consistency,obfus_number_series,obfuscation,majority,answered,7
20,self_consistency,obfus_number_series,obfuscation,none,no_consensus,2
21,self_consistency,obfus_number_series,obfuscation,unanimous,answered,41

{'model': 'gpt-5.6-sol',
 'reasoning_effort': 'high',
 'conditions': 7,
 'task_variant_cells': 45,
 'evaluation_units': 2250,
 'raw_model_generations': 3600,
 'completed_evaluations': 2250,
 'status_counts': {'answered': 2243, 'no_consensus': 7},
 'scoring_policy': 'Parent-package task normalizers with digit/word Blood Relation count equivalence; Direction distance tolerance is 0.05.',
 'condition_totals': [{'condition': 'normalize_then_solve',
   'scope': 'all applicable variants',
   'correct': 181,
   'total': 250,
   'accuracy_pct': 72.4},
  {'condition': 'normalize_then_solve',
   'scope': 'obfuscated variants',
   'correct': 98,
   'total': 150,
   'accuracy_pct': 65.3333},
  {'condition': 'structured_decomposition',
   'scope': 'all applicable variants',
   'correct': 146,
   'total': 250,
   'accuracy_pct': 58.4},
  {'condition': 'structured_decomposition',
   'scope': 'obfuscated variants',
   'correct': 84,
   'total': 150,
   'accuracy_pct': 56.0},
  {'condition': 'explicit_task_instructions',
   'scope': 'all applicable variants',
   'correct': 125,
   'total': 200,
   'accuracy_pct': 62.5},
  {'condition': 'explicit_task_instructions',
   'scope': 'obfuscated variants',
   'correct': 60,
   'total': 100,
   'accuracy_pct': 60.0},
  {'condition': 'chain_of_thought',
   'scope': 'all applicable variants',
   'correct': 326,
   'total': 450,
   'accuracy_pct': 72.4444},
  {'condition': 'chain_of_thought',
   'scope': 'obfuscated variants',
   'correct': 176,
   'total': 250,
   'accuracy_pct': 70.4},
  {'condition': 'rereading_s2a',
   'scope': 'all applicable variants',
   'correct': 151,
   'total': 200,
   'accuracy_pct': 75.5},
  {'condition': 'rereading_s2a',
   'scope': 'obfuscated variants',
   'correct': 71,
   'total': 100,
   'accuracy_pct': 71.0},
  {'condition': 'self_consistency',
   'scope': 'all applicable variants',
   'correct': 310,
   'total': 450,
   'accuracy_pct': 68.8889},
  {'condition': 'self_consistency',
   'scope': 'obfuscated variants',
   'correct': 162,
   'total': 250,
   'accuracy_pct': 64.8},
  {'condition': 'self_verification_cove',
   'scope': 'all applicable variants',
   'correct': 306,
   'total': 450,
   'accuracy_pct': 68.0},
  {'condition': 'self_verification_cove',
   'scope': 'obfuscated variants',
   'correct': 163,
   'total': 250,
   'accuracy_pct': 65.2}],
 'special_metrics': {'self_consistency': {'evaluations': 450,
   'raw_paths': 1350,
   'agreement_counts': {'unanimous': 382, 'majority': 61, 'none': 7},
   'agreement_rate_pct': 98.4444},
  'self_verification_cove': {'evaluations': 450,
   'raw_passes': 900,
   'answer_changed': 6,
   'answer_change_rate_pct': 1.3333,
   'incorrect_to_correct': 1,
   'correct_to_incorrect': 5}}}

{'self_consistency_evaluations': 450,
 'self_consistency_raw_paths': 1350,
 'self_consistency_agreement': {'unanimous': 382, 'majority': 61, 'none': 7},
 'cove_evaluations': 450,
 'cove_raw_passes': 900,
 'cove_answers_changed': 6}